
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\school\InventoryManagement\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("900x600")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 600,
    width = 900,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    675.0,
    300.0,
    image=image_image_1
)

canvas.create_rectangle(
    0.0,
    0.0,
    454.0,
    600.0,
    fill="#FFFFFF",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    242.5,
    293.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=31.0,
    y=267.0,
    width=423.0,
    height=51.0
)

canvas.create_text(
    31.0,
    250.0,
    anchor="nw",
    text="Password:",
    fill="#000000",
    font=("Inter Medium", 16 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    242.5,
    385.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=31.0,
    y=359.0,
    width=423.0,
    height=51.0
)

canvas.create_text(
    31.0,
    342.0,
    anchor="nw",
    text="Confirm Password:",
    fill="#000000",
    font=("Inter Medium", 16 * -1)
)

canvas.create_text(
    104.0,
    50.0,
    anchor="nw",
    text="Create Account",
    fill="#000000",
    font=("Inter Bold", 36 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    242.5,
    201.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=31.0,
    y=175.0,
    width=423.0,
    height=51.0
)

canvas.create_text(
    31.0,
    156.0,
    anchor="nw",
    text="Username:",
    fill="#000000",
    font=("Inter Medium", 17 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=53.0,
    y=445.0,
    width=379.0,
    height=51.0
)
window.resizable(False, False)
window.mainloop()
