
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\school\Tkinter-Designer\build\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("900x600")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 600,
    width = 900,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    900.0,
    79.0,
    fill="#82FB7C",
    outline="")

canvas.create_text(
    35.0,
    28.0,
    anchor="nw",
    text="Welcome back,",
    fill="#000000",
    font=("Inter Bold", 20 * -1)
)

canvas.create_rectangle(
    0.0,
    79.0,
    900.0,
    600.0,
    fill="#FFFFFF",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    705.0,
    39.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=562.0,
    y=18.0,
    width=286.0,
    height=41.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=848.0,
    y=18.0,
    width=43.0,
    height=43.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=832.0,
    y=107.0,
    width=33.0,
    height=33.0
)

canvas.create_text(
    35.0,
    107.0,
    anchor="nw",
    text="All Items: 100",
    fill="#000000",
    font=("Inter Medium", 16 * -1)
)

canvas.create_rectangle(
    35.0,
    150.0,
    867.0,
    577.0,
    fill="#FFFFFF",
    outline="")

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    132.5,
    218.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FF0000",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=48.0,
    y=197.0,
    width=169.0,
    height=41.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    608.0,
    218.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#8AFC8F",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=569.0,
    y=197.0,
    width=78.0,
    height=41.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    713.5,
    218.5,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFEA2D",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=647.0,
    y=197.0,
    width=133.0,
    height=41.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    357.0,
    218.5,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#C931FF",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=217.0,
    y=197.0,
    width=280.0,
    height=41.0
)

canvas.create_rectangle(
    35.0,
    150.0,
    867.0,
    187.0,
    fill="#F5F5F5",
    outline="")

canvas.create_text(
    48.0,
    156.0,
    anchor="nw",
    text="Item name",
    fill="#000000",
    font=("Inter Bold", 14 * -1)
)

canvas.create_text(
    222.0,
    156.0,
    anchor="nw",
    text="Item description",
    fill="#000000",
    font=("Inter Bold", 14 * -1)
)

canvas.create_text(
    497.0,
    156.0,
    anchor="nw",
    text="Quantity",
    fill="#000000",
    font=("Inter Bold", 14 * -1)
)

canvas.create_text(
    575.0,
    156.0,
    anchor="nw",
    text="Price",
    fill="#000000",
    font=("Inter Bold", 14 * -1)
)

canvas.create_text(
    653.0,
    156.0,
    anchor="nw",
    text="Expire dates",
    fill="#000000",
    font=("Inter Bold", 14 * -1)
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=799.0,
    y=202.0,
    width=33.0,
    height=33.0
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    132.5,
    218.5,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#FF0000",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=48.0,
    y=197.0,
    width=169.0,
    height=41.0
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    713.5,
    218.5,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#FFEA2D",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=647.0,
    y=197.0,
    width=133.0,
    height=41.0
)

entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    357.0,
    218.5,
    image=entry_image_8
)
entry_8 = Entry(
    bd=0,
    bg="#C931FF",
    fg="#000716",
    highlightthickness=0
)
entry_8.place(
    x=217.0,
    y=197.0,
    width=280.0,
    height=41.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=799.0,
    y=202.0,
    width=33.0,
    height=33.0
)

entry_image_9 = PhotoImage(
    file=relative_to_assets("entry_9.png"))
entry_bg_9 = canvas.create_image(
    608.0,
    261.5,
    image=entry_image_9
)
entry_9 = Entry(
    bd=0,
    bg="#267429",
    fg="#000716",
    highlightthickness=0
)
entry_9.place(
    x=569.0,
    y=240.0,
    width=78.0,
    height=41.0
)

entry_image_10 = PhotoImage(
    file=relative_to_assets("entry_10.png"))
entry_bg_10 = canvas.create_image(
    132.5,
    261.5,
    image=entry_image_10
)
entry_10 = Entry(
    bd=0,
    bg="#FF0000",
    fg="#000716",
    highlightthickness=0
)
entry_10.place(
    x=48.0,
    y=240.0,
    width=169.0,
    height=41.0
)

entry_image_11 = PhotoImage(
    file=relative_to_assets("entry_11.png"))
entry_bg_11 = canvas.create_image(
    713.5,
    261.5,
    image=entry_image_11
)
entry_11 = Entry(
    bd=0,
    bg="#7F7411",
    fg="#000716",
    highlightthickness=0
)
entry_11.place(
    x=647.0,
    y=240.0,
    width=133.0,
    height=41.0
)

entry_image_12 = PhotoImage(
    file=relative_to_assets("entry_12.png"))
entry_bg_12 = canvas.create_image(
    357.0,
    261.5,
    image=entry_image_12
)
entry_12 = Entry(
    bd=0,
    bg="#73009B",
    fg="#000716",
    highlightthickness=0
)
entry_12.place(
    x=217.0,
    y=240.0,
    width=280.0,
    height=41.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=799.0,
    y=245.0,
    width=33.0,
    height=33.0
)

canvas.create_text(
    510.0,
    197.0,
    anchor="nw",
    text="23",
    fill="#000000",
    font=("Inter", 16 * -1)
)

canvas.create_text(
    510.0,
    240.0,
    anchor="nw",
    text="23",
    fill="#000000",
    font=("Inter", 16 * -1)
)
window.resizable(False, False)
window.mainloop()
